# Generated by Django 4.2.5 on 2023-09-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_lc_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lc_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
